data_url : "https://drive.google.com/uc?id=1zTLGDZ2N6uGP0nTLX0JPXEaJq-1h2SwT"
data_folder: "data"

wandb_params:
  project_name: "fraud_detection"
  entity: "zuozhe"


training_params:
  n_folds: 5
  n_jobs: -1


models:
  LGBMClassifier:
    n_estimators: [500, 700, 1000]
    learning_rate: [0.01]
    objective: ["binary"]
    metric: ['average_precision']
    is_unbalance: [True]
  RandomForestClassifier:
    n_estimators: [100, 125]
  LogisticRegression:
    penalty: ['l2']
    C: [0.8,1.0,1.2]
    fit_intercept: [True, False]
  LinearSVC:
    penalty: ['l2']
    C: [0.8,1.0,1.2]
    fit_intercept: [True, False]

optuna:
  n_trials: 25

production_model:
  LGBMClassifier:
    n_estimators: 
      type: "int"
      low: 1400
      high: 2300
    learning_rate: 
      type: "uniform"
      low: 0.0001
      high: 0.025
    # max_depth: 
    #   type: "int"
    #   low: 5
    #   high: 17
    min_split_gain : 
      type: "uniform"
      low: 0.0001
      high: 0.07
    objective: 
      type: "category"
      choices: ["binary"]
    metric: 
      type: "category"
      choices: ['average_precision']
    is_unbalance: 
      type: "category"
      choices: [True]
  

metrics:
  optimizing_metric: test_average_precision # AUC under PR curve
  tracking_metrics: ["average_precision", "f1", "precision", "recall", "roc_auc", "accuracy"]
